package br.com.guarani.rta.entidade;

public enum TipoAtributo {
		
	TELEFONE, CNPJ, CPF,  DATA, CEP, EMBALAGEM, FRETE, SN, ESTADO_SEPARADO_PONTOVIRGULA, TIPO_PESSOA, TRATA_LIMITE_CREDITO, TIPO_COMISSAO, POLITICA_PRECOS, PRAZO_MINIMO, TIPO_PROD_CLI,
	CODIGO_POR_PONTOVIRGULA;
		
}
